--- src/Makefile	(.../vendor/vim/current)	(revision 223)
+++ src/Makefile	(.../trunk/vim)	(revision 223)
@@ -412,6 +412,9 @@
 # WORKSHOP - Sun Visual Workshop interface.  Only works with Motif!
 #CONF_OPT_WORKSHOP = --enable-workshop
 
+# GDB - Include support for gdb
+CONF_OPT_GDB = --enable-gdb
+
 # NETBEANS - NetBeans interface. Only works with Motif, GTK, and gnome.
 # Motif version must have XPM libraries (see |workshop-xpm|).
 # Uncomment this when you do not want the netbeans interface.
@@ -1414,12 +1417,14 @@
 
 SRC =	$(BASIC_SRC) $(GUI_SRC) $(HANGULIN_SRC) $(MZSCHEME_SRC) \
 	$(PERL_SRC) $(PYTHON_SRC) $(TCL_SRC) $(RUBY_SRC) \
+	$(GDB_SRC) \
 	$(SNIFF_SRC) $(WORKSHOP_SRC) $(WSDEBUG_SRC)
 
 TAGS_SRC = *.c *.cpp if_perl.xs
 
 EXTRA_SRC = hangulin.c if_mzsch.c auto/if_perl.c if_perlsfio.c \
 	    if_python.c if_tcl.c if_ruby.c if_sniff.c gui_beval.c \
+		gdb.c clewn/gdb_lvl2.c clewn/gdb_lvl3.c clewn/misc.c clewn/obstack.c \
 	    workshop.c wsdebug.c integration.c netbeans.c
 
 # All sources, also the ones that are not configured
@@ -1429,6 +1434,7 @@
 # checks more, but may not work well for checking a GUI that wasn't configured.
 # The perl sources also don't work well with lint.
 LINT_SRC = $(BASIC_SRC) $(GUI_SRC) $(HANGULIN_SRC) $(PYTHON_SRC) $(TCL_SRC) \
+	$(GDB_SRC) \
 	$(SNIFF_SRC) $(WORKSHOP_SRC) $(WSDEBUG_SRC) $(NETBEANS_SRC)
 #LINT_SRC = $(SRC)
 #LINT_SRC = $(ALL_SRC)
@@ -1489,6 +1495,7 @@
 	$(RUBY_OBJ) \
 	$(OS_EXTRA_OBJ) \
 	$(WORKSHOP_OBJ) \
+	$(GDB_OBJ) \
 	$(NETBEANS_OBJ) \
 	$(WSDEBUG_OBJ)
 
@@ -1544,6 +1551,7 @@
 	window.pro \
 	gui_beval.pro \
 	workshop.pro \
+	gdb.pro \
 	netbeans.pro \
 	$(ALL_GUI_PRO) \
 	$(TCL_PRO)
@@ -1577,6 +1585,7 @@
 		$(CONF_OPT_TCL) $(CONF_OPT_RUBY) $(CONF_OPT_NLS) \
 		$(CONF_OPT_CSCOPE) $(CONF_OPT_MULTIBYTE) $(CONF_OPT_INPUT) \
 		$(CONF_OPT_OUTPUT) $(CONF_OPT_GPM) $(CONF_OPT_WORKSHOP) \
+		$(CONF_OPT_GDB) \
 		$(CONF_OPT_SNIFF) $(CONF_OPT_FEAT) $(CONF_TERM_LIB) \
 		$(CONF_OPT_COMPBY) $(CONF_OPT_ACL)  $(CONF_OPT_NETBEANS) \
 		$(CONF_ARGS) $(CONF_OPT_MZSCHEME) $(CONF_OPT_PLTHOME) \
@@ -2552,6 +2561,21 @@
 objects/workshop.o: workshop.c
 	$(CCC) -o $@ workshop.c
 
+objects/gdb.o: gdb.c
+	$(CCC) -o $@ gdb.c
+
+objects/gdb_lvl2.o: clewn/gdb_lvl2.c
+	$(CCC) -o $@ clewn/gdb_lvl2.c
+
+objects/gdb_lvl3.o: clewn/gdb_lvl3.c
+	$(CCC) -o $@ clewn/gdb_lvl3.c
+
+objects/misc.o: clewn/misc.c
+	$(CCC) -o $@ clewn/misc.c
+
+objects/obstack.o: clewn/obstack.c
+	$(CCC) -o $@ clewn/obstack.c
+
 objects/wsdebug.o: wsdebug.c
 	$(CCC) -o $@ wsdebug.c
 
@@ -2948,6 +2972,13 @@
   os_unix.h auto/osdef.h ascii.h keymap.h term.h macros.h option.h \
   structs.h regexp.h gui.h gui_beval.h proto/gui_beval.pro ex_cmds.h \
   proto.h globals.h farsi.h arabic.h version.h workshop.h
+objects/gdb.o: gdb.c clewn/gdb.h clewn/misc.h auto/config.h vim.h feature.h
+objects/gdb_lvl2.o: clewn/misc.h clewn/gdb_lvl2.c clewn/gdb_lvl3.c \
+	gdb.c clewn/gdb.h auto/config.h vim.h feature.h
+objects/gdb_lvl3.o: clewn/misc.h clewn/gdb_lvl3.c gdb.c clewn/gdb.h\
+	auto/config.h vim.h feature.h
+objects/misc.o: clewn/misc.c clewn/misc.h
+objects/obstack.o: clewn/obstack.c clewn/obstack.h
 objects/wsdebug.o: wsdebug.c
 objects/integration.o: integration.c vim.h auto/config.h feature.h os_unix.h \
   auto/osdef.h ascii.h keymap.h term.h macros.h option.h structs.h \
